Namma_bazaar/Namma_bazaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls'))
]+static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Namma_bazaar/carts/urls.py
from django.urls import path,include
from carts import views

urlpatterns = [
    path('', views.cart_page, name='cart_page'),
    path('add-cart/<int:product_id>/', views.add_cart, name='add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove-cart-item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
    ]

Namma_bazaar/store/urls.py
from django.urls import path
from store import views

urlpatterns = [
    
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name= 'products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name= 'product_detail'),
    path('search/',views.search, name='search'),

               
               
               
               ]

Namma_bazaar/carts/models.py
from django.db import models
from store.models import product,product_variation


# Create your models here.

class cart( models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    added_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    
class cartItem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    variation=models.ManyToManyField(product_variation,blank=True)
    cart=models.ForeignKey(cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    is_active=models.BooleanField(default=True)

    def __unicode__(self):
        return self.product
    
    def sub_total(self):
        return self.product.price * self.quantity
    

Namma_bazaar/store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse

# Create your models here.

class product (models.Model):
    product_name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=200,unique=True)
    description=models.TextField(max_length=500,blank=True)
    price=models.IntegerField()
    images=models.ImageField(upload_to='photos/products')
    stocks=models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.product_name
    
    def get_url (self):
        return reverse ('product_detail', args=[self.category.slug,self.slug])
    
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color', is_active=  True)
    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size', is_active=True)


variation_choices=(('color','color'),('size','size'))
class product_variation(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    variation_category=models.CharField( max_length=50,choices=variation_choices)
    variation_name=models.CharField(max_length=50)
    is_active=models.BooleanField(default=True)

    def __str__(self): 
        return self.variation_name
    
    objects=VariationManager()

Namma_bazaar/carts/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from store.models import product,product_variation
from carts.models import cart,cartItem
# Create your views here.


def _cart_id(request):
    session_id = request.session.session_key
    if not session_id:
        session_id = request.session.create()
      # Assign the newly created session key
    return session_id



def add_cart (request,product_id):
    products=product.objects.get(id=product_id)
    product_variations=[]

    if request.method=='POST':
        for items in request.POST:
            key=items
            value=request.POST[key]
            try:
                variation_list=product_variation.objects.get(product=products, variation_category__iexact=key, variation_name__iexact=value)
                product_variations.append(variation_list)
            except:
                pass

    try:
        Cart=cart.objects.get(cart_id=_cart_id(request))
    except cart.DoesNotExist:
        Cart=cart.objects.create(
            cart_id=_cart_id(request)
        )
        Cart.save()



    is_cart_item_exists= cartItem.objects.filter(product=products,cart=Cart).exists()
    if is_cart_item_exists:
        cart_item=cartItem.objects.filter(product=products, cart=Cart)
        #need 1. existing variations 2. product variation(want to add) 3.item_id
        ex_var_list=[]
        id=[]
        for item in cart_item:
            existing_variation=item.variation.all()
            ex_var_list.append(list(existing_variation))
            id.append(item.id)

        if product_variations in ex_var_list:
            index=ex_var_list.index(product_variations)
            item_id=id[index]
            item=cartItem.objects.get(product=products, id=item_id)
            item.quantity = item.quantity + 1 
            item.save()
                # increase quantity
        else:
            item=cartItem.objects.create(product=products, cart=Cart, quantity=1)
            if len(product_variations) > 0 :
                item.variation.clear()
                item.variation.add(*product_variations)
            item.save()

    else :
        cart_item=cartItem.objects.create(
            product=products,
            cart=Cart,
            quantity=1,
        )
        if len(product_variations) > 0 :
            cart_item.variation.clear()
            cart_item.variation.add(*product_variations)
        cart_item.save()
    return redirect ('cart_page')

def remove_cart(request,product_id,cart_item_id ):
    Cart=cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)

    try:
        cart_item=cartItem.objects.get(cart=Cart,product=products, id=cart_item_id)
        if cart_item.quantity > 1 :
            cart_item.quantity -=1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect ('cart_page')


def remove_cart_item (request,product_id,cart_item_id):
    Cart=cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item=cartItem.objects.get(cart=Cart,product=products,id=cart_item_id)
    cart_item.delete()
    return redirect('cart_page')

    

def cart_page (request,total=0,quantity=0,cart_item=None):
    try:
        Cart=cart.objects.get(cart_id=_cart_id(request))
        cart_item=cartItem.objects.filter(cart=Cart,is_active=True)
        for cart_items in cart_item:
            total=total + (cart_items.product.price * cart_items.quantity)
            quantity= quantity + cart_items.quantity
        tax= (3*total/100)
        grand_total=total+tax
        
    except :
        pass

    context={
        'cart_items':cart_item,
        'quantity':quantity,
        'total':total,
        'tax':tax,
        'grand_total':grand_total,
    }
    return render (request,'store/cart.html',context)

Namma_bazaar/store/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from store.models import product
from category.models import Category
from carts.models import cartItem
from carts.views import _cart_id

def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug is not None:
        categories = get_object_or_404(Category,slug=category_slug) #It will bring requested category
        products = product.objects.filter(category=categories, is_available=True)
         #It'll filter the products from above selected category
        paginators=Paginator(products,1)
        page=request.GET.get('page')
        page_product=paginators.get_page(page)
        product_count = products.count()
    else:
        products = product.objects.filter(is_available=True)
        product_count = products.count()
        paginators=Paginator(products,3)
        page=request.GET.get('page')
        page_product=paginators.get_page(page)

    context = {'products': page_product, 'product_count': product_count}

    return render(request, 'store/store.html', context)


def product_detail(request,category_slug,product_slug):
    try:
        single_product=product.objects.get(category__slug=category_slug, slug=product_slug)
        incart=cartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()


    except Exception as e :
        raise e
    context={'single_product':single_product, 'incart':incart}

    return render(request,'store/product_detail.html',context)

def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            products=product.objects.order_by('-created_date').filter(Q(description__icontains=keyword)| Q (product_name__icontains=keyword))
    product_count = products.count()

                                                                
    context={'products':products,'product_count': product_count}

    return render (request,'store/store.html', context)

Namma_bazaar/templates/store/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
<h2 class="text-center text-primary-light"> Please add something to your cart </h2>


{% else  %}
  
  
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items %}
  
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
				<p class="text-muted small"> 
					{% if cart_item.variation.all %}
						{% for i in cart_item.variation.all  %}
							{{i.variation_category}} : {{i.variation_name}}
							{% if not forloop.last %}, {% endif %} <!-- Add comma if not the last variation -->

						{% endfor %}
					  
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'remove-cart' cart_item.product.id cart_item.id  %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{cart_item.quantity}}">
							<div class="input-group-append">
								<form action="{% url 'add-cart' cart_item.product.id %}" method="POST">
									{% csrf_token %}
									{% for item in cart_item.variation.all %}
									<input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_name | capfirst }}">
									  
									{% endfor %}
									<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>

								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$ {{cart_item.sub_total}}</var> 
			<small class="text-muted"> {{cart_item.product.price}} </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'remove-cart-item' cart_item.product.id cart_item.id %}" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}

</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">$ {{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> $ {{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static 'images/misc/payments.png' %}" height="26">
			</p>
			<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
{% endif %}

{% endblock %}

Namma_bazaar/templates/store/product_detail.html
{% extends "base.html" %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src={{single_product.images.url}}></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">

  <form action="{% url 'add-cart' single_product.id %}" method="POST">
    {% csrf_token %}

    <article class="content-body">
    
    <h2 class="title">{{single_product.product_name}}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">$ {{single_product.price}}</var> 
    </div> 
    
    <p>{{single_product.description}}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                  <option value="" disabled>select</option>

                  {% for i in single_product.product_variation_set.colors %}
                  <option value="{{i.variation_name | lower}}">{{i.variation_name|capfirst}}</option>
                  {% endfor %}
                 
                </select>
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">

                <h6>Select Size</h6>
                <select name="size" class="form-control">
                  <option value="" disabled>select</option>

                  {% for i in single_product.product_variation_set.sizes %}
                  
                  <option value="{{i.variation_name | lower}}">{{i.variation_name|capfirst}}</option>
                    
                  {% endfor %}
                </select>
                
            </div>
        </div> <!-- row.// -->
        <hr>
        {% if single_product.stocks <= 0 %}
        <h5 class='text-danger'>*out of stock*</h5>
        {% else %}
          
        <button class="btn btn-primary" type="submit"> Add to cart</button>

        {% endif %}
    </article>
  </form>
   <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
{% endblock %}

Namma_bazaar/templates/store/store.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Our Store</h2>


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                        <li class="font-weight-bolder"><a href="{% url 'store' %}">All products</a></li>


                        {% for category in links %}
                        <li><a href="{{category.get_url}}">{{category.category_name}} </a></li>

                        {% endfor %}
                    
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto"><b>{{product_count}}</b> Items found </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">
        {% if products %}
        {% for product in products %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    
                    <a href="{{product.get_url}}"><img src="{{product.images.url}}"></a>
                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
                        <div class="price-wrap mt-2">
                            <span class="price">$ {{product.price}}</span>
                        </div> <!-- price-wrap.// -->
                    </div>
                    <a href="{% url 'add-cart' product.id %}" class="btn btn-block btn-primary"> View Item </a>
                </figcaption>
            </figure>
        </div> <!-- col.// -->
          
        {% endfor %}
        {% else %}
        <h2 class="text-center">No result found. Try again <i class="fa fa-thumbs-up text-success" aria-hidden="true"></i></h2>          
        {% endif %}


    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
    {% if products.has_other_pages %}
          
      <ul class="pagination">
        {% if products.has_previous %} 
        
        <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
        {% else  %}
        <li class="page-item disabled "><a class="page-link" href="#">Previous</a></li>

        {% endif %}

        {% for i in products.paginator.page_range  %}
            {% if products.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
        {% endfor %}



        {% if products.has_next %} 
            <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
        {% else %}
            <li class="page-item disabled "><a class="page-link" href="#">Next</a></li>          
        {% endif %}
        
      </ul>

    {% endif %}

    </nav>
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->





{% endblock %}